const loadingAnimationTime = '10s';

module.exports = {
  content: ['./src/**/**/**.tsx'],
  theme: {
    screens: {
      md: { raw: '(min-width: 768px) and (min-height: 450px)' },
    },
    extend: {
      borderRadius: {
        inherit: 'inherit',
        sm: '0.25rem',
      },
      boxShadow: {
        sm: 'var(--box-shadow-sm)',
        md: 'var(--box-shadow-md)',
        lg: 'var(--box-shadow-lg)',
        xl: 'var(--box-shadow-xl)',
      },
      fontFamily: {
        primary: ['var(--font-family-primary)'],
      },
      maxHeight: {
        contentCard: '34.25rem',
        87: '21.75rem',
      },
      height: {
        18: '4.5rem',
        35: '8.75rem',
        54: '13.5rem',
      },
      width: {
        18: '4.5rem',
        35: '8.75rem',
        63: '15.75rem',
        88: '22rem',
      },
      minWidth: {
        xs: '15.625rem',
      },
      maxWidth: {
        xs: '17rem',
        md: '25rem',
        '2xl': '40rem',
        '60-screen': '60vw',
      },
      zIndex: {
        max: '9999',
      },
      colors: {
        grayscale: {
          100: 'var(--color-grayscale-100)',
          200: 'var(--color-grayscale-200)',
          300: 'var(--color-grayscale-300)',
          400: 'var(--color-grayscale-400)',
          500: 'var(--color-grayscale-500)',
          600: 'var(--color-grayscale-600)',
          700: 'var(--color-grayscale-700)',
          800: 'var(--color-grayscale-800)',
          900: 'var(--color-grayscale-900)',
        },
        primary: {
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
        },
        secondary: {
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
        },
        neutral: {
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
        },
        error: {
          100: 'var(--color-error-100)',
          200: 'var(--color-error-200)',
          300: 'var(--color-error-300)',
          400: 'var(--color-error-400)',
          500: 'var(--color-error-500)',
          600: 'var(--color-error-600)',
          700: 'var(--color-error-700)',
          800: 'var(--color-error-800)',
          900: 'var(--color-error-900)',
        },
      },
      animation: {
        grow: 'grow 1.2s ease-in-out infinite',
        spread: 'spread 1.6s ease-in-out infinite',
        countTo25: `countTo25 ${loadingAnimationTime} linear forwards`,
        countFrom25To50: `countfrom25To50 ${loadingAnimationTime} linear forwards`,
        countFrom50To75: `countFrom50To75 ${loadingAnimationTime} linear forwards`,
        countFrom75To100: `countFrom75To100 ${loadingAnimationTime} linear forwards`,
        fillTo25: `fillTo25 ${loadingAnimationTime} linear forwards`,
        fillFrom25To50: `fillFrom25To50 ${loadingAnimationTime} linear forwards`,
        fillFrom50To75: `fillFrom50To75 ${loadingAnimationTime} linear forwards`,
        fillFrom75To100: `fillFrom75To100 ${loadingAnimationTime} linear forwards`,
      },
      keyframes: {
        grow: {
          '0%': { transform: 'scaleY(.3)' },
          '50%': { transform: 'scaleY(1)' },
          '100%': { transform: 'scaleY(.3)' },
        },
        spread: {
          '0%': { columnGap: '2px' },
          '50%': { columnGap: '4px' },
          '100%': { columnGap: '2px' },
        },
        countTo25: {
          '0%': { counterIncrement: 'count 0' },
          '10%': { counterIncrement: 'count 3' },
          '20%': { counterIncrement: 'count 6' },
          '30%': { counterIncrement: 'count 8' },
          '40%': { counterIncrement: 'count 10' },
          '50%': { counterIncrement: 'count 12' },
          '60%': { counterIncrement: 'count 15' },
          '70%': { counterIncrement: 'count 18' },
          '80%': { counterIncrement: 'count 20' },
          '90%': { counterIncrement: 'count 23' },
          '100%': { counterIncrement: 'count 25' },
        },
        countfrom25To50: {
          '0%': { counterIncrement: 'count 25' },
          '10%': { counterIncrement: 'count 27' },
          '20%': { counterIncrement: 'count 30' },
          '30%': { counterIncrement: 'count 33' },
          '40%': { counterIncrement: 'count 36' },
          '50%': { counterIncrement: 'count 39' },
          '60%': { counterIncrement: 'count 41' },
          '70%': { counterIncrement: 'count 44' },
          '80%': { counterIncrement: 'count 46' },
          '90%': { counterIncrement: 'count 48' },
          '100%': { counterIncrement: 'count 50' },
        },
        countFrom50To75: {
          '0%': { counterIncrement: 'count 50' },
          '10%': { counterIncrement: 'count 52' },
          '20%': { counterIncrement: 'count 55' },
          '30%': { counterIncrement: 'count 58' },
          '40%': { counterIncrement: 'count 61' },
          '50%': { counterIncrement: 'count 64' },
          '60%': { counterIncrement: 'count 66' },
          '70%': { counterIncrement: 'count 68' },
          '80%': { counterIncrement: 'count 70' },
          '90%': { counterIncrement: 'count 72' },
          '100%': { counterIncrement: 'count 75' },
        },
        countFrom75To100: {
          '0%': { counterIncrement: 'count 75' },
          '10%': { counterIncrement: 'count 77' },
          '20%': { counterIncrement: 'count 80' },
          '30%': { counterIncrement: 'count 82' },
          '40%': { counterIncrement: 'count 85' },
          '50%': { counterIncrement: 'count 87' },
          '60%': { counterIncrement: 'count 89' },
          '70%': { counterIncrement: 'count 91' },
          '80%': { counterIncrement: 'count 92' },
          '90%': { counterIncrement: 'count 95' },
          '100%': { counterIncrement: 'count 100' },
        },
        fillTo25: {
          from: { width: '0' },
          to: { width: '25%' },
        },
        fillFrom25To50: {
          from: { width: '25%' },
          to: { width: '50%' },
        },
        fillFrom50To75: {
          from: { width: '50%' },
          to: { width: '75%' },
        },
        fillFrom75To100: {
          from: { width: '75%' },
          to: { width: '100%' },
        },
      },
    },
  },
  plugins: [
    function ({ addVariant }) {
      addVariant('children', '& > *');
    },
  ],
  prefix: 'sm-',
  corePlugins: {
    preflight: false,
  },
};
