const loadingAnimationTime = '15s';

module.exports = {
  content: ['./src/**/**/**.tsx'],
  theme: {
    screens: {
      md: { raw: '(min-width: 768px) and (min-height: 450px)' },
    },
    extend: {
      borderRadius: {
        inherit: 'inherit',
        sm: '0.25rem',
      },
      boxShadow: {
        sm: 'var(--box-shadow-sm)',
        md: 'var(--box-shadow-md)',
        lg: 'var(--box-shadow-lg)',
        xl: 'var(--box-shadow-xl)',
      },
      fontFamily: {
        primary: ['var(--font-family-primary)'],
      },
      maxHeight: {
        contentCard: '34.25rem',
        87: '21.75rem',
      },
      height: {
        18: '4.5rem',
        35: '8.75rem',
        54: '13.5rem',
      },
      width: {
        18: '4.5rem',
        35: '8.75rem',
        63: '15.75rem',
        88: '22rem',
      },
      minWidth: {
        xs: '15.625rem',
      },
      maxWidth: {
        xs: '17rem',
        md: '25rem',
        '2xl': '40rem',
        '60-screen': '60vw',
      },
      zIndex: {
        max: '9999',
      },
      colors: {
        grayscale: {
          100: 'var(--color-grayscale-100)',
          200: 'var(--color-grayscale-200)',
          300: 'var(--color-grayscale-300)',
          400: 'var(--color-grayscale-400)',
          500: 'var(--color-grayscale-500)',
          600: 'var(--color-grayscale-600)',
          700: 'var(--color-grayscale-700)',
          800: 'var(--color-grayscale-800)',
          900: 'var(--color-grayscale-900)',
        },
        primary: {
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
        },
        secondary: {
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
        },
        neutral: {
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
        },
        error: {
          100: 'var(--color-error-100)',
          200: 'var(--color-error-200)',
          300: 'var(--color-error-300)',
          400: 'var(--color-error-400)',
          500: 'var(--color-error-500)',
          600: 'var(--color-error-600)',
          700: 'var(--color-error-700)',
          800: 'var(--color-error-800)',
          900: 'var(--color-error-900)',
        },
      },
      animation: {
        grow: 'grow 1.2s ease-in-out infinite',
        spread: 'spread 1.6s ease-in-out infinite',
        countTo33: `countTo33 ${loadingAnimationTime} linear forwards`,
        countFrom33To66: `countfrom33To66 ${loadingAnimationTime} linear forwards`,
        countFrom66To100: `countFrom66To100 ${loadingAnimationTime} linear forwards`,
        fillTo33: `fillTo33 ${loadingAnimationTime} linear forwards`,
        fillFrom33To66: `fillFrom33To66 ${loadingAnimationTime} linear forwards`,
        fillFrom66To100: `fillFrom66To100 ${loadingAnimationTime} linear forwards`,
      },
      keyframes: {
        grow: {
          '0%': { transform: 'scaleY(.3)' },
          '50%': { transform: 'scaleY(1)' },
          '100%': { transform: 'scaleY(.3)' },
        },
        spread: {
          '0%': { columnGap: '2px' },
          '50%': { columnGap: '4px' },
          '100%': { columnGap: '2px' },
        },
        countTo33: {
          '0%': { counterIncrement: 'count 0' },
          '10%': { counterIncrement: 'count 3' },
          '20%': { counterIncrement: 'count 9' },
          '30%': { counterIncrement: 'count 11' },
          '40%': { counterIncrement: 'count 14' },
          '50%': { counterIncrement: 'count 18' },
          '60%': { counterIncrement: 'count 21' },
          '70%': { counterIncrement: 'count 24' },
          '80%': { counterIncrement: 'count 27' },
          '90%': { counterIncrement: 'count 20' },
          '100%': { counterIncrement: 'count 33' },
        },
        countfrom33To66: {
          '0%': { counterIncrement: 'count 33' },
          '10%': { counterIncrement: 'count 36' },
          '20%': { counterIncrement: 'count 39' },
          '30%': { counterIncrement: 'count 42' },
          '40%': { counterIncrement: 'count 45' },
          '50%': { counterIncrement: 'count 50' },
          '60%': { counterIncrement: 'count 54' },
          '70%': { counterIncrement: 'count 57' },
          '80%': { counterIncrement: 'count 60' },
          '90%': { counterIncrement: 'count 63' },
          '100%': { counterIncrement: 'count 66' },
        },
        countFrom66To100: {
          '0%': { counterIncrement: 'count 66' },
          '10%': { counterIncrement: 'count 70' },
          '20%': { counterIncrement: 'count 73' },
          '30%': { counterIncrement: 'count 75' },
          '40%': { counterIncrement: 'count 79' },
          '50%': { counterIncrement: 'count 83' },
          '60%': { counterIncrement: 'count 87' },
          '70%': { counterIncrement: 'count 91' },
          '80%': { counterIncrement: 'count 92' },
          '90%': { counterIncrement: 'count 95' },
          '100%': { counterIncrement: 'count 100' },
        },
        fillTo33: {
          from: { width: '0' },
          to: { width: '33%' },
        },
        fillFrom33To66: {
          from: { width: '33%' },
          to: { width: '66%' },
        },
        fillFrom66To100: {
          from: { width: '66%' },
          to: { width: '100%' },
        },
      },
    },
  },
  plugins: [
    function ({ addVariant }) {
      addVariant('children', '& > *');
    },
  ],
  prefix: 'sm-',
  corePlugins: {
    preflight: false,
  },
};
