name: Build for Gallery

on:
  workflow_dispatch:
  push:
    branches:
      - ENG-1146-use-smwebsdk-from-repo-and-workflow
    
permissions:
  contents: read # Required for checkout the source code

jobs:
  release:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set Version
        id: RELEASE_VERSION
        run: |
          version=$(git rev-parse --short HEAD)
          echo "::set-output name=tag::${version}"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'

      - name: Caching Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build
        env:
          NODE_ENV: production
          # Since we are not using semantic release in dev, use the commit hash for versioning so its traceable
          VERSION: ${{ steps.RELEASE_VERSION.outputs.tag }}

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-gallery
          path: dist
          # retention-days: 90
