name: PR check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'

      - name: Caching Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Create Release File
      - uses: actions/checkout@v2
        # Get all tags in latest order and pipe it into a json file { "versions": [ "1.4.0", "1.3.0", "1.2.0" ] }
      - run: |
          echo git tag  --sort=-v:refname

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test:ci

      - name: Run Prettier
        run: npm run prettier

      - name: Build Package
        run: npm run build
