name: Cypress UI Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Version
        id: RELEASE_VERSION
        run: |
          version=$(git rev-parse --short HEAD)
          echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: npm ci

      - run: npm run build:example
        env:
          # Since we are not using semantic release in dev, use the commit hash for versioning so its traceable
          VERSION: ${{ steps.RELEASE_VERSION.outputs.tag }}

      # Upload build folder to be used in subsequent jobs (run-chrome, run-edge etc)
      - name: Save dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          if-no-files-found: error
          path: dist

  cypress-run-chrome:
    runs-on: ubuntu-latest
    needs: build
    container: cypress/included:14.1.0
    # Cancel job in 15mins if it has not completed
    timeout-minutes: 15
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run copies of the current job in parallel, [1,2] runs 2 instances
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Cypress run on Chrome
        uses: cypress-io/github-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          browser: chrome
          start: npm run serve
          wait-on: 'http://localhost:5050/'
          config-file: cypress.config.ts
          spec: cypress/e2e/*.ts
          record: true
          parallel: true
          # Groups the tests in the dashboard under this label
          group: 'UI - Chrome'

  cypress-run-edge:
    runs-on: ubuntu-latest
    needs: build
    container: cypress/included:14.1.0
    # Cancel job in 15mins if it has not completed
    timeout-minutes: 15
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run copies of the current job in parallel, [1,2,3,4,5] runs 5 instances
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Cypress run on Chrome
        uses: cypress-io/github-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          browser: edge
          start: npm run serve
          wait-on: 'http://localhost:5050/'
          config-file: cypress.config.ts
          spec: cypress/e2e/*.ts
          record: true
          parallel: true
          group: 'UI - Edge'
