name: Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Caching dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      # - name: Run tests
      #   run: npm run test

      - name: Run prettier
        run: npm run prettier

      - name: Build assets
        run: npm run package

      - name: Archive assets
        uses: actions/upload-artifact@v2
        with:
          name: soulmachines.js
          path: demo/soulmachines.js

  deploy:
    if: github.ref == 'refs/heads/release/*'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download assets
        uses: actions/download-artifact@v2
        with:
          name: soulmachines.js

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: 'us-east-1'

      - name: Deploy to S3 Bucket
        run: aws s3 cp ./soulmachines.js s3://static.soulmachines.com/soulmachines-1.0.0-rc.0.js
