name: Release Stable

on:
  workflow_dispatch:

env:
  ASSET_LOCATION: dist
  AWS_PATH: 's3://static-prod.soulmachines.com'
  AWS_DEFAULT_OUTPUT: 'json'
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_ROLE_ARN: arn:aws:iam::924390807111:role/static_sm_com_GHA_Role
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.RELEASE_VERSION.outputs.tag }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'

      - name: Caching Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Create Release
        id: RELEASE_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.SMGITHUBBOT_REPO_COMMIT }}
        run: |
          npx semantic-release
          echo $(git describe --abbrev=0 --tags)
          version=$(git describe --abbrev=0 --tags)
          echo "::set-output name=tag::${version}"

      - name: Build Package
        run: npm run build
        env:
          NODE_ENV: production
          CDN_ENDPOINT: 'https://static.soulmachines.com/'
          VERSION: ${{ needs.build.outputs.RELEASE_VERSION }}

      - name: Version Snippet
        env:
          VERSION: ${{ needs.build.outputs.RELEASE_VERSION }}
          # take latest files and create a copy with the current version number
        run: |
          cp "dist/widget-snippet-latest.js" "dist/widget-snippet-${{ env.VERSION }}.js"
          cp "dist/widget-snippet-latest.min.js" "dist/widget-snippet-${{ env.VERSION }}.min.js"

      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Release to CDN
        run: |
          aws s3 cp --sse AES256 ${{ env.ASSET_LOCATION }} ${{ env.AWS_PATH }}/ --recursive
          aws cloudfront create-invalidation --distribution-id=${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
          echo "release done"
