name: Release

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onevent_nametypes
on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Caching dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      # - name: Run tests
      #   run: npm run test

      - name: Run prettier
        run: npm run prettier

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build assets
        run: npm run package

      - name: Archive assets
        uses: actions/upload-artifact@v2
        with:
          name: sm-web-component
          path: demo/soulmachines.js

  # deploy:
  #   needs: [build, verify]
  #   runs-on: ubuntu-latest
  #   if: github.ref === 'refs/heads/master'

  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: sm-web-component

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: <<YOUR REGION HERE>>

  #     - name: Deploy to S3 Bucket
  #       run: aws s3 sync ./ s3://<<YOUR S3 BUCKET NAME HERE>>
